export const drinkList = [
  {
    id: "1",
    name: "Basil Bramble",
    descricao: "gin, limão siciliano, licor de amora, manjericão e açúcar.",
    image: require("../../assets/drinks/basil-bramble.png"),
    receita: [
      "25ml limão siciliano",
      "7 folhas de manjericão",
      "50ml gin",
      "30ml licor de amora",
      "25ml açúcar",
      "Bater na Coqueteleira",
    ],
    taca: "Copo Long",
  },
  {
    id: "2",
    name: "Lagoa Azul",
    descricao: "vodka, sprite, curaçau blue, limão e açúcar.",
    image: require("../../assets/drinks/lagoa-azul.png"),
    receita: [
      "50ml vodka",
      "25ml curaçau blue",
      "25ml limão taiti",
      "10ml açúcar",
      "Bater na Coqueteleira",
      "60ml sprite (completar)",
    ],
    taca: "Hurricane",
  },
  {
    id: "3",
    name: "Lagoa Verde",
    descricao: "vodka, limão siciliano, suco de abacaxi e licor de menta.",
    image: require("../../assets/drinks/lagoa-verde.png"),
    receita: [
      "Preencher com Gelo",
      "60ml vodka",
      "20ml limão siciliano",
      "150ml suco de abacaxi",
      "20ml licor de menta",
      "Misturar",
    ],
    taca: "Hurricane",
  },
  {
    id: "4",
    name: "Alexander",
    descricao: "conhaque, creme de leite, creme de cacau e canela.",
    image: require("../../assets/drinks/alexander.png"),
    receita: [
      "30ml conhaque",
      "30ml creme de leite",
      "30ml licor de cacau",
      "Bater na Coqueteleira",
      "Canela",
    ],
    taca: "Martini",
  },
  {
    id: "5",
    name: "Grasshopper",
    descricao: "licor de menta, licor de cacau e creme de leite.",
    image: require("../../assets/drinks/grasshopper.png"),
    receita: [
      "50ml creme de leite",
      "50ml licor de menta",
      "30ml licor de cacau",
      "Bater na Coqueteleira",
      "Chocolate Ralado",
    ],
    taca: "Martini",
  },
  {
    id: "6",
    name: "Clover Club",
    descricao: "gin, ovo, limão siciliano, morango e açúcar.",
    image: require("../../assets/drinks/clover-club.png"),
    receita: [
      "6 morangos grandes",
      "30ml limão siciliano",
      "20ml açúcar",
      "60ml gin",
      "1 clara de ovo",
      "3x dry shake",
      "Bater na Coqueteleira",
    ],
  },
  {
    id: "7",
    name: "Piña Colada",
    descricao: "rum, leite de coco, suco de abacaxi e leite condensado.",
    image: require("../../assets/drinks/pina-colada.png"),
    receita: [
      "60ml rum",
      "30ml leite de coco",
      "90ml suco de abacaxi",
      "50ml leite condensado",
      "Bater na Coqueteleira",
      "Calda de Chocolate",
    ],
    taca: "Hurricane",
  },
  {
    id: "8",
    name: "Blue Hawaii",
    descricao: "rum, suco de abacaxi, curaçau blue, leite de coco e açúcar.",
    image: require("../../assets/drinks/blue-hawaii.png"),
    receita: [
      "3 colheres açúcar",
      "100ml suco de abacaxi",
      "50ml rum",
      "50ml curaçau blue",
      "50ml leite de coco",
      "Bater na Coqueteleira",
    ],
    taca: "Margarita",
  },
  {
    id: "9",
    name: "Rum Flip",
    descricao: "rum, ovo, creme de leite, açúcar e noz moscada.",
    image: require("../../assets/drinks/rum-flip.png"),
    receita: [
      "1 Ovo",
      "20ml açúcar",
      "25ml creme de leite",
      "50ml rum",
      "3x dry shake",
      "Bater na Coqueteleira",
      "Noz Moscada",
    ],
  },
  {
    id: "10",
    name: "Bramble",
    descricao: "gin, limão siciliano, licor de amora e açúcar.",
    image: require("../../assets/drinks/bramble.png"),
    receita: [
      "50ml gin",
      "25ml açúcar",
      "25ml limão siciliano",
      "Bater na Coqueteleira",
      "Gelo picado",
      "20ml licor de amora",
    ],
    taca: "Copo Long",
  },
  {
    id: "11",
    name: "Mojito de Coco",
    descricao: "rum, malibu, curaçau blue, limão, hortelã e açúcar.",
    image: require("../../assets/drinks/mojito-coco.png"),
    receita: [
      "10 hortelãs grandes",
      "25ml açúcar",
      "50ml malibu",
      "35ml rum",
      "15ml limão",
      "Completar água com gás",
      "10ml curaçau blue",
    ],
  },
  {
    id: "12",
    name: "Cuba Libre",
    descricao: "rum, coca-cola e limão.",
    image: require("../../assets/drinks/cuba-libre.png"),
    receita: [
      "Preencher com Gelo",
      "50ml rum",
      "Refri (completar)",
      "Espremer limão taiti",
      "Misturar",
    ],
    taca: "Caneca",
  },
  {
    id: "13",
    name: "Coconut Blue",
    descricao:
      "malibu, curaçau blue, leite de coco, suco de abacaxi e coco ralado.",
    image: require("../../assets/drinks/coconut-blue.png"),
    receita: [
      "75ml malibu",
      "50ml leite de coco",
      "50ml suco de abacaxi",
      "25ml curacau blue",
      "Bater na Coqueteleira",
      "Coco Ralado",
    ],
    taca: "Martini",
  },
  {
    id: "14",
    name: "Caribeño Drink",
    descricao: "rum, água de coco, limão e açúcar.",
    image: require("../../assets/drinks/coconut.png"),
    receita: [
      "60ml rum",
      "5ml limão taiti",
      "25ml açúcar",
      "120ml água de coco",
      "Preencher com Gelo",
      "Misturar",
    ],
    taca: "Caneca",
  },
  {
    id: "15",
    name: "Carnadrink",
    descricao:
      "vodka, suco de abacaxi, leite de coco, leite condensado e confete.",
    image: require("../../assets/drinks/carnadrink.png"),
    receita: [
      "50ml vodka",
      "50ml leite condensado",
      "50ml leite de coco",
      "100ml suco de abacaxi",
      "Bater na Coqueteleira",
      "Confete",
    ],
    taca: "Martini",
  },
];
