export const drinkList = [
  {
    id: "1",
    name: "Basil Bramble",
    descricao: "gin, limão siciliano, licor de amora, manjericão e açúcar.",
    image: require(`../assets/img/drinks/basil-bramble.jpg`),
    receita: [
      { id: 1, name: "25ml limão siciliano", icon: require(`../assets/img/icons/siciliano.png`) },
      { id: 2, name: "7 folhas de manjericão", icon: require(`../assets/img/icons/manjericao.png`) },
      { id: 3, name: "50ml gin", icon: require(`../assets/img/icons/gin.png`) },
      { id: 4, name: "30ml licor de amora", icon: require(`../assets/img/icons/amora.png`) },
      { id: 5, name: "25ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 6, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
    ],
    taca: "Copo Long",
  },
  {
    id: "2",
    name: "Lagoa Azul",
    descricao: "vodka, sprite, curaçau blue, limão e açúcar.",
    image: require(`../assets/img/drinks/lagoa-azul.jpg`),
    receita: [
      { id: 7, name: "50ml vodka", icon: require(`../assets/img/icons/vodka.png`) },
      { id: 8, name: "25ml curaçau blue", icon: require(`../assets/img/icons/curacau.png`) },
      { id: 9, name: "25ml limão taiti", icon: require(`../assets/img/icons/taiti.png`) },
      { id: 10, name: "10ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 11, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 12, name: "60ml sprite (completar)", icon: require(`../assets/img/icons/sprite.png`) },
    ],
    taca: "Hurricane",
  },
  {
    id: "3",
    name: "Lagoa Verde",
    descricao: "vodka, limão siciliano, suco de abacaxi e licor de menta.",
    image: require(`../assets/img/drinks/lagoa-verde.jpg`),
    receita: [
      { id: 13, name: "Preencher com Gelo", icon: require(`../assets/img/icons/gelo.png`) },
      { id: 14, name: "60ml vodka", icon: require(`../assets/img/icons/vodka.png`) },
      { id: 15, name: "20ml limão siciliano", icon: require(`../assets/img/icons/siciliano.png`) },
      { id: 16, name: "150ml suco de abacaxi", icon: require(`../assets/img/icons/abacaxi.png`) },
      { id: 17, name: "20ml licor de menta", icon: require(`../assets/img/icons/menta.png`) },
      { id: 18, name: "Misturar", icon: require(`../assets/img/icons/misturar.png`) },
    ],
    taca: "Hurricane",
  },
  {
    id: "4",
    name: "Alexander",
    descricao: "conhaque, creme de leite, creme de cacau e canela.",
    image: require(`../assets/img/drinks/alexander.jpg`),
    receita: [
      { id: 19, name: "30ml conhaque", icon: require(`../assets/img/icons/conhaque.png`) },
      { id: 20, name: "30ml creme de leite", icon: require(`../assets/img/icons/creme-leite.png`) },
      { id: 21, name: "30ml licor de cacau", icon: require(`../assets/img/icons/cacau.png`) },
      { id: 22, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 23, name: "Canela", icon: require(`../assets/img/icons/canela.png`) },
    ],
    taca: "Martini",
  },
  {
    id: "5",
    name: "Grasshopper",
    descricao: "licor de menta, licor de cacau e creme de leite.",
    image: require(`../assets/img/drinks/grasshoper.jpg`),
    receita: [
      { id: 24, name: "50ml creme de leite", icon: require(`../assets/img/icons/creme-leite.png`) },
      { id: 25, name: "50ml licor de menta", icon: require(`../assets/img/icons/menta.png`) },
      { id: 26, name: "30ml licor de cacau", icon: require(`../assets/img/icons/cacau.png`) },
      { id: 27, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 28, name: "Chocolate Ralado", icon: require(`../assets/img/icons/chocolate.png`) },
    ],
    taca: "Martini",
  },
  {
    id: "6",
    name: "Clover Club",
    descricao: "gin, ovo, limão siciliano, morango e açúcar.",
    image: require(`../assets/img/drinks/clover-club.jpg`),
    receita: [
      { id: 29, name: "6 morangos grandes", icon: require(`../assets/img/icons/morango.png`) },
      { id: 30, name: "30ml limão siciliano", icon: require(`../assets/img/icons/siciliano.png`) },
      { id: 31, name: "20ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 32, name: "60ml gin", icon: require(`../assets/img/icons/gin.png`) },
      { id: 33, name: "1 clara de ovo", icon: require(`../assets/img/icons/ovo.png`) },
      { id: 34, name: "3x dry shake", icon: require(`../assets/img/icons/dry-shake.png`) },
      { id: 35, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
    ],
    taca: "Margarita",
  },
  {
    id: "7",
    name: "Piña Colada",
    descricao: "rum, leite de coco, suco de abacaxi e leite condensado.",
    image: require(`../assets/img/drinks/pina-colada.jpg`),
    receita: [
      { id: 36, name: "60ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 37, name: "30ml leite de coco", icon: require(`../assets/img/icons/leite-de-coco.png`) },
      { id: 38, name: "90ml suco de abacaxi", icon: require(`../assets/img/icons/abacaxi.png`) },
      { id: 39, name: "50ml leite condensado", icon: require(`../assets/img/icons/leite-condensado.png`) },
      { id: 40, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 41, name: "Calda de Chocolate", icon: require(`../assets/img/icons/calda.png`) },
    ],
    taca: "Hurricane",
  },
  {
    id: "8",
    name: "Blue Hawaii",
    descricao: "rum, suco de abacaxi, curaçau blue, leite de coco e açúcar.",
    image: require(`../assets/img/drinks/blue-hawaii.jpg`),
    receita: [
      { id: 42, name: "3 colheres açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 43, name: "100ml suco de abacaxi", icon: require(`../assets/img/icons/abacaxi.png`) },
      { id: 44, name: "50ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 45, name: "50ml curaçau blue", icon: require(`../assets/img/icons/curacau.png`) },
      { id: 46, name: "50ml leite de coco", icon: require(`../assets/img/icons/leite-de-coco.png`) },
      { id: 47, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
    ],
    taca: "Margarita",
  },
  {
    id: "9",
    name: "Rum Flip",
    descricao: "rum, ovo, creme de leite, açúcar e noz moscada.",
    image: require(`../assets/img/drinks/rum-flip.jpg`),
    receita: [
      { id: 48, name: "1 Ovo", icon: require(`../assets/img/icons/ovo.png`) },
      { id: 49, name: "20ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 50, name: "25ml creme de leite", icon: require(`../assets/img/icons/creme-leite.png`) },
      { id: 51, name: "50ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 52, name: "3x dry shake", icon: require(`../assets/img/icons/dry-shake.png`) },
      { id: 53, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 54, name: "Noz Moscada", icon: require(`../assets/img/icons/noz.png`) },
    ],
    taca: "Margarita",
  },
  {
    id: "10",
    name: "Bramble",
    descricao: "gin, limão siciliano, licor de amora e açúcar.",
    image: require(`../assets/img/drinks/bramble.jpg`),
    receita: [
      { id: 55, name: "50ml gin", icon: require(`../assets/img/icons/gin.png`) },
      { id: 56, name: "25ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 57, name: "25ml limão siciliano", icon: require(`../assets/img/icons/siciliano.png`) },
      { id: 58, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 59, name: "Gelo picado", icon: require(`../assets/img/icons/gelo.png`) },
      { id: 60, name: "20ml licor de amora", icon: require(`../assets/img/icons/amora.png`) },
    ],
    taca: "Copo Long",
  },
  {
    id: "11",
    name: "Mojito de Coco",
    descricao: "rum, malibu, curaçau blue, limão, hortelã e açúcar.",
    image: require(`../assets/img/drinks/mojito-coco.jpg`),
    receita: [
      { id: 61, name: "10 hortelãs grandes", icon: require(`../assets/img/icons/hortela.png`) },
      { id: 62, name: "25ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 63, name: "50ml malibu", icon: require(`../assets/img/icons/malibu.png`) },
      { id: 64, name: "35ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 65, name: "15ml limão", icon: require(`../assets/img/icons/taiti.png`) },
      { id: 66, name: "Completar água com gás", icon: require(`../assets/img/icons/agua-com-gas.png`) },
      { id: 67, name: "10ml curaçau blue", icon: require(`../assets/img/icons/curacau.png`) },
    ],
    taca: "Copo Long",
  },
  {
    id: "12",
    name: "Cuba Libre",
    descricao: "rum, coca-cola e limão.",
    image: require(`../assets/img/drinks/cuba-libre.jpg`),
    receita: [
      { id: 68, name: "Preencher com Gelo", icon: require(`../assets/img/icons/gelo.png`) },
      { id: 69, name: "50ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 70, name: "Refri (completar)", icon: require(`../assets/img/icons/coca.png`) },
      { id: 71, name: "Espremer limão taiti", icon: require(`../assets/img/icons/taiti.png`) },
      { id: 72, name: "Misturar", icon: require(`../assets/img/icons/misturar.png`) },
    ],
    taca: "Caneca",
  },
  {
    id: "13",
    name: "Coconut Blue",
    descricao: "malibu, curaçau blue, leite de coco, suco de abacaxi e coco ralado.",
    image: require(`../assets/img/drinks/coconut.jpg`),
    receita: [
      { id: 73, name: "75ml malibu", icon: require(`../assets/img/icons/malibu.png`) },
      { id: 74, name: "50ml leite de coco", icon: require(`../assets/img/icons/leite-de-coco.png`) },
      { id: 75, name: "50ml suco de abacaxi", icon: require(`../assets/img/icons/abacaxi.png`) },
      { id: 76, name: "25ml curacau blue", icon: require(`../assets/img/icons/curacau.png`) },
      { id: 77, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 78, name: "Coco Ralado", icon: require(`../assets/img/icons/coco.png`) },
    ],
    taca: "Martini",
  },
  {
    id: "14",
    name: "Caribeño Drink",
    descricao: "rum, água de coco, limão e açúcar.",
    image: require(`../assets/img/drinks/caribeno.jpg`),
    receita: [
      { id: 79, name: "60ml rum", icon: require(`../assets/img/icons/rum.png`) },
      { id: 80, name: "5ml limão taiti", icon: require(`../assets/img/icons/taiti.png`) },
      { id: 81, name: "25ml açúcar", icon: require(`../assets/img/icons/acucar.png`) },
      { id: 82, name: "120ml água de coco", icon: require(`../assets/img/icons/coco.png`) },
      { id: 83, name: "Preencher com Gelo", icon: require(`../assets/img/icons/gelo.png`) },
      { id: 84, name: "Misturar", icon: require(`../assets/img/icons/misturar.png`) },
    ],
    taca: "Caneca",
  },
  {
    id: "15",
    name: "Carnadrink",
    descricao: "vodka, suco de abacaxi, leite de coco, leite condensado e confete.",
    image: require(`../assets/img/drinks/carnadrink.jpg`),
    receita: [
      { id: 85, name: "50ml vodka", icon: require(`../assets/img/icons/vodka.png`) },
      { id: 86, name: "50ml leite condensado", icon: require(`../assets/img/icons/leite-condensado.png`) },
      { id: 87, name: "50ml leite de coco", icon: require(`../assets/img/icons/leite-de-coco.png`) },
      { id: 88, name: "100ml suco de abacaxi", icon: require(`../assets/img/icons/abacaxi.png`) },
      { id: 89, name: "Bater na Coqueteleira", icon: require(`../assets/img/icons/coqueteleira.png`) },
      { id: 90, name: "Confete", icon: require(`../assets/img/icons/confete.png`) },
    ],
    taca: "Martini",
  },
];
