export const drinkList = [
  {
    id: "1",
    name: "Bramble",
    descricao: "gin, limão siciliano, licor de amora e açúcar.",
    image: require("../../assets/drinks/generic-drink.png"),
    receita: [
      "50ml gin",
      "25ml açúcar",
      "25ml limão siciliano",
      "20ml licor de amora",
    ],
  },
  {
    id: "2",
    name: "Lagoa Azul",
    descricao: "vodka, sprite, curaçau blue, limão e açúcar.",
    image: require("../../assets/drinks/lagoa-azul.png"),
    receita: [
      "50ml vodka",
      "25ml curaçau blue",
      "25ml limão taiti",
      "10ml açúcar",
      "60ml sprite",
    ],
  },
  {
    id: "3",
    name: "Lagoa Verde",
    descricao: "vodka, limão siciliano, suco de abacaxi e licor de menta.",
    image: require("../../assets/drinks/lagoa-verde.png"),
    receita: [
      "60ml vodka",
      "20ml limão siciliano",
      "150ml suco de abacaxi",
      "20ml licor de menta",
    ],
  },
  {
    id: "4",
    name: "Alexander",
    descricao: "conhaque, creme de leite e creme de cacau.",
    image: require("../../assets/drinks/alexander.png"),
    receita: ["30ml conhaque", "30ml creme de leite", "30ml licor de cacau"],
  },
  {
    id: "5",
    name: "Grasshopper",
    descricao: "licor de menta, licor de cacau e creme de leite.",
    image: require("../../assets/drinks/grasshopper.png"),
    receita: [
      "50ml creme de leite",
      "50ml licor de menta",
      "30ml licor de cacau",
    ],
  },
  {
    id: "6",
    name: "Piña Colada",
    descricao: "rum, leite de coco, suco de abacaxi e leite condensado.",
    image: require("../../assets/drinks/pina-colada.png"),
    receita: [
      "60ml rum",
      "30ml leite de coco",
      "90ml suco de abacaxi",
      "50ml leite condensado",
      "chocolate",
    ],
  },
  {
    id: "7",
    name: "Blue Hawaii",
    descricao: "rum, suco de abacaxi, curaçau blue, leite de coco e açúcar.",
    image: require("../../assets/drinks/blue-hawaii.png"),
    receita: [
      "50ml rum",
      "100ml suco de abacaxi",
      "50ml curaçau blue",
      "50ml leite de coco",
      "3 colheres açúcar",
    ],
  },
  {
    id: "8",
    name: "Caribeño Drink",
    descricao: "rum, água de coco, limão e açúcar.",
    image: require("../../assets/drinks/coconut.png"),
    receita: [
      "60ml rum",
      "5ml limão taiti",
      "25ml açúcar",
      "120ml água de coco",
    ],
  },
  {
    id: "9",
    name: "Cuba Libre",
    descricao: "rum, coca-cola e limão.",
    image: require("../../assets/drinks/cuba-libre.png"),
    receita: ["50ml rum", "1/2 limão taiti", "Refri (completar)"],
  },
];
